### ISSUE TITLE
MAINT: tracker for `sensitivity_indices`

### ISSUE THREAD

**Issue by tupui** [tupui/scipy#14]
Some ideas for follow up of https://github.com/scipy/scipy/pull/17628

- [ ] batch function evaluations
- [ ] Check for NaN and raise
- [ ] other method for bootstraping if too slow
- [ ] other methods for indices
- [ ] other GSA methods (moment independent, DGSM)
- [ ] Higer order
- [ ] Tutorial on SA
